### ISSUE TITLE
Font Probelm with PMingLiU

### ISSUE THREAD

**Issue by huhanwj** [huhanwj/GECW-4010#1]
get warning msg as

Font "PMingLiU" does not contain requested Script
(fontspec)	"CJK".`

Some font shapes were not available, defaults substituted.

Font shape `TU/ntxtlf/m/n' undefined
(Font)	using `TU/lmr/m/n' instead.

**Comment by Zhmjharmgal** [comment]
Yes, I have the same warning message on my local machine.

**Comment by huhanwj** [comment]
fixed with remove wrongly used packet
