### ISSUE TITLE
Section Font Beautify?

### ISSUE THREAD

**Issue by huhanwj** [huhanwj/GECW-4010#2]
Add Bold to the sections?
@Zhmjharmgal 
give comparison in the following comments

**Comment by Zhmjharmgal** [comment]
With bold titles, the article more resembles the one in the .doc file.
Without bold, the size of the titles is only larger than the contents.

**Comment by huhanwj** [comment]
> 
> 
> With bold titles, the article more resembles the one in the .doc file.
> Without bold, the size of the titles is only larger than the contents.

Give some screenshots.

**Comment by huhanwj** [comment]
@Zhmjharmgal 换font之后这个问题解决，根本原因和 #1 一致，是XeLateX缺某些英文字体的原因
