### ISSUE TITLE
Contents

### ISSUE THREAD

**Issue by huhanwj** [huhanwj/GECW-4010#4]
Abstract and section 1.1 done
Pic1 needed source
Pic1,2 &3  and Graph 1&2 need insertion and formatting

**Comment by huhanwj** [comment]
@Zhmjharmgal pls record here after each update

**Comment by huhanwj** [comment]
Recent commit just finished all the text contents in our interim report.
Missing citation and graphical contents.

**Comment by Zhmjharmgal** [comment]
传了图

**Comment by huhanwj** [comment]
paper引用的bib做好了，接下来是把网页和图片的各种bib也生成一下

**Comment by huhanwj** [comment]
图片添加，网页ref添加

**Comment by Zhmjharmgal** [comment]
删了pdf，更新了gitignore

**Comment by Zhmjharmgal** [comment]
加了questionnaire 2

**Comment by huhanwj** [comment]
整合了分析结果，Section2 表格添加完毕
缺图片排版和各种图标上
缺conclusion

> 
> 
> 加了questionnaire 2

**Comment by huhanwj** [comment]
wording proposed by两位苦手男士done
现在先主攻graphs，我去趟百佳弄点吃的
@Zhmjharmgal

**Comment by huhanwj** [comment]
还缺一个ref + 表格 source
@Zhmjharmgal
